# Generated by Django 5.2.6 on 2026-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('alphabet', 'Алфавит'), ('professions', 'Профессии'), ('animals', 'Животные'), ('colors', 'Цвета')], max_length=20)),
                ('word', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='URL картинки (можно использовать placeholder)')),
            ],
        ),
    ]
