# Generated by Django 5.2.6 on 2026-02-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievement_remove_word_image_url_word_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
    ]
